### PR TITLE
Pirania: add read_for_access mode

### PR DESCRIPTION
**Pull request by germanferrero**
This PR allow to use Pirania's captive portal without vouchers. In a Read for Access mode, in which the user enters  captive portal splash page and needs to wait for 15 seconds and then continue navigating for a default of 15 min, configurable at `pirania.read_for_access.duration_m` in minutes.

### CODE REVIEW

**Comment by spiccinini** [comment]
Great work! I think for this it is better if we use `utils.uptime_s()` instead of a timestamp as the uptime is monotonic and we don't need to "survive reboots". What do you think?

**Comment by germanferrero** [comment]
> Great work! I think for this it is better if we use `utils.uptime_s()` instead of a timestamp as the uptime is monotonic and we don't need to "survive reboots". What do you think?

That will work too, yes!

**Comment by germanferrero** [comment]
> Great work! I think for this it is better if we use `utils.uptime_s()` instead of a timestamp as the uptime is monotonic and we don't need to "survive reboots". What do you think?
 
Done!

**Comment by spiccinini** [comment]
> TODO:
> 
>     * Redirection to previous url works, but it get's catched by pirania again. Timming between requests and captive portal update has to be reviewed.

This is fixed when removing keep alive right?

**Comment by germanferrero** [comment]
> This is fixed when removing keep alive right?

yes, I forgot to update the  description

**Pull request merged**
